import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is defined manually so the long "Operational guides" section can
 * be grouped into collapsible folders. The top-level "flat label" sections
 * (AI Control Room, Concepts) keep their original look: they are non-collapsible
 * level-1 categories whose contents are still generated from the folder
 * structure (via each folder's _category_.json).
 *
 * The Operational-guides folders are intentionally given NO `link`, so clicking
 * a folder label only expands/collapses it (Notion-style) and no `/category/...`
 * index page is generated. The caret is styled in src/css/sidebar.css.
 *
 * No files are moved and no doc URLs change: pages are referenced by id.
 */
const sidebars: SidebarsConfig = {
	docsSidebar: [
		// Flat label: AI Control Room (contents generated from docs/cr)
		{
			type: "category",
			label: "AI Control Room",
			collapsible: false,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "cr" }],
		},

		// Flat label: Operational guides, grouped into folders
		{
			type: "category",
			label: "Operational guides",
			collapsible: false,
			collapsed: false,
			items: [
				"operational-guides/get-started",
				{
					type: "category",
					label: "Setup & data",
					collapsed: true,
					items: [
						"operational-guides/integrate-data",
						"operational-guides/configure-sources",
						"operational-guides/configure-connectors",
					],
				},
				{
					type: "category",
					label: "Knowledge",
					collapsed: true,
					items: [
						"operational-guides/create-knowledge",
						"operational-guides/import-knowledge",
						"operational-guides/export-knowledge",
						"operational-guides/manage-knowledge-resources",
						"operational-guides/annotate-resources",
						"operational-guides/sqlite-resource-database",
						"operational-guides/configure-rag",
						"operational-guides/knowledge-custom-views",
						"operational-guides/embed-knowledge",
					],
				},
				{
					type: "category",
					label: "Models & AI",
					collapsed: true,
					items: [
						"operational-guides/ai-model-registry-features",
						"operational-guides/fine-tune-a-model",
					],
				},
				{
					type: "category",
					label: "Conversations & channels",
					collapsed: true,
					items: [
						"operational-guides/chat-experience",
						"operational-guides/configure-touchpoints",
						"operational-guides/manage-channels",
						"operational-guides/conversations",
						"operational-guides/conversation-processing",
					],
				},
				{
					type: "category",
					label: "Workflows",
					collapsed: true,
					items: [
						"operational-guides/create-workflow",
						"operational-guides/create-processing-rule",
						"operational-guides/workflow-rules",
					],
				},
				{
					type: "category",
					label: "Extend",
					collapsed: true,
					items: [
						"operational-guides/build-an-extension",
						"operational-guides/manage-extensions",
						"operational-guides/manage-tools",
						"operational-guides/agent-skills",
					],
				},
				{
					type: "category",
					label: "Rational BI",
					collapsed: true,
					items: ["operational-guides/rational-bi"],
				},
				{
					type: "category",
					label: "Administration",
					collapsed: true,
					items: [
						"operational-guides/roles-and-users",
						"operational-guides/personalize-user-details",
						"operational-guides/governance",
					],
				},
				{
					type: "category",
					label: "API",
					collapsed: true,
					items: [
						"operational-guides/api-access",
						"operational-guides/api/deploy-open-source-models",
					],
				},
			],
		},

		// Flat label: Concepts (contents generated from docs/concepts)
		{
			type: "category",
			label: "Concepts",
			collapsible: false,
			collapsed: false,
			items: [{ type: "autogenerated", dirName: "concepts" }],
		},
	],
};

export default sidebars;
